model:
  model_name: csta
  dim: 512
  num_heads: 8
  num_layers: 8

data:
  dataset_name: ucf101
  num_frames: 8
  img_size: 112
  num_channels: 3
  patch_size: 16
  root_dir: DATA/UCF101
  train_csv: DATA/UCF101/tasks/task_1/train.csv
  test_csv: DATA/UCF101/tasks/task_1/test.csv
  valid_csv: DATA/UCF101/tasks/task_1/val.csv

loss:
  calculate_distil_loss: True
  calculate_lt_ls_loss: True
  count_relations: True
  miu_d: 0.15
  miu_t: 0.15
  miu_s: 0.15
  lambda_1: 0.2
  lambda_2: 0.2
  K: 5
  temporal_features_path: model_save/smaller_model/bank/task_0_model/temporal_feats_task1.pt
  spatial_features_path: model_save/smaller_model/bank/task_0_model/spatial_feats_task1.pt
  temporal_relations_path: model_save/smaller_model/bank/task_0_model/temporal_relations_task1.json
  spatial_relations_path: model_save/smaller_model/bank/task_0_model/spatial_relations_task1.json

task:
  task_n: 1
  init_with_adapters: False
  num_classes_t0: 51
  num_classes_new: 10

train:
  random_seed: 42
  num_training_epochs: 50
  training_batch_size: 32
  evaluation_batch_size: 32
  dataloader_num_workers: 4
  dataloader_pin_memory: False
  dataloader_persistent_workers: False
  learning_rate: 1e-4
  weight_decay: 1e-4
  eta_min: 1e-10
  warmup_epochs: 2
  max_grad: 1.5
  early_stop_patience: 5

checkpoints:
  old_config_path: model_save/smaller_model/ucf101/task_0
  old_checkpoint: model_save/test/test_task0.pth