model:
  model_name: csta
  dim: 512
  num_layers: 12
  num_heads: 8

data:
  dataset_name: ucf101
  num_frames: 8
  img_size: 16
  num_channels: 3
  patch_size: 16
  root_dir: DATA/UCF101
  train_csv: DATA/UCF101/tasks/task_0/train.csv
  test_csv: DATA/UCF101/tasks/task_0/test.csv
  valid_csv: DATA/UCF101/tasks/task_0/val.csv

loss:
  calculate_distil_loss: False
  calculate_lt_ls_loss: False
  count_relations: False
  miu_d: 0.1
  miu_t: 0.1
  miu_s: 0.1
  lambda_1: 0.2
  K: 5
  count_relations: False
  temporal_relations_path: null
  spatial_relations_path: null

task:
  task_n: 0
  init_with_adapters: False
  num_classes_t0: 50

train:
  random_seed: 42
  num_training_epochs: 80
  training_batch_size: 7
  evaluation_batch_size: 7
  dataloader_num_workers: 4
  dataloader_pin_memory: False
  dataloader_persistent_workers: False
  learning_rate: 1e-5
  adamw_betas: (0.9, 0.999)
  weight_decay: 0.1
  eta_min: 1e-10
  warmup_epochs: 12