model:
  model_name: csta
  dim: 512
  num_heads: 8
  num_layers: 8

data:
  dataset_name: ucf101
  num_frames: 8
  img_size: 112
  num_channels: 3
  patch_size: 16
  root_dir: DATA/UCF101
  train_csv: DATA/UCF101/tasks/task_1/train.csv
  test_csv: DATA/UCF101/tasks/task_1/test.csv
  valid_csv: DATA/UCF101/tasks/task_1/val.csv
  label2id_path: DATA/UCF101/tasks/label2id.json

loss:
  calculate_distil_loss: True
  calculate_lt_ls_loss: True
  count_relations: True
  miu_d: 0.15
  miu_t: 0.15
  miu_s: 0.15
  lambda_1: 0.2
  lambda_2: 0.2
  K: 5
  temporal_features_path: model_save/new_trial/bank/task_0_model/temporal_feats_task0.pt
  spatial_features_path: model_save/new_trial/bank/task_0_model/spatial_feats_task0.pt
  temporal_relations_path: model_save/new_trial/bank/task_0_model/temporal_relations_task0.json
  spatial_relations_path: model_save/new_trial/bank/task_0_model/spatial_relations_task0.json

task:
  task_n: 1
  init_with_adapters: False
  num_classes_t0: 51
  num_classes_new: 10

train:
  random_seed: 42
  num_training_epochs: 50
  training_batch_size: 32
  evaluation_batch_size: 32
  dataloader_num_workers: 4
  dataloader_pin_memory: False
  dataloader_persistent_workers: False
  learning_rate: 1e-5
  weight_decay: 1e-4
  eta_min: 1e-10
  warmup_epochs: 5
  max_grad: 1.5
  early_stop_patience: 5

checkpoints:
  old_config_path: model_save/new_trial/ucf101/task_0/config/train_config.yml
  old_checkpoint: model_save/new_trial/ucf101/task_0/model/checkpoints/final_model.pth

fine_tune:
  fine_tune: True
  unfreeze: False
  train_data_0: DATA/UCF101/tasks/task_0/fine_tune.csv
  train_data_1: DATA/UCF101/tasks/task_1/fine_tune.csv
  task_n_ft: 0
  ft_epochs: 20
